

// console.log(3 + 5);

// //Operaciones de comparación
// console.log (4 < 7); 
// console.log (4 < 1 );
// console.log (4 > 4); 
// console.log (4 == 7);

// //Igualdad vs igualdad estricta 
// console.log (3 == 3); 
// console.log (3 === 3); 
// console.log (3 == "3"); 
// console.log (3 === "3");
// console.log (7 == "7");
// console.log (7 === "7");
// //Asignación y asociatividad

// //Asignación y asociatividad
// //var a = 1;
// var b = 2;
// var c = a = b;
// console.log (c); 

//FUNCIONES

// function sumaprueba(x){
//  console.log(x+3);
// }
// //Función: sumaTres
// var sumaTres = (x) => {
//     return x + 3;
//   }
// sumaprueba(6)
// sumaTres(2)
function viajar(destino) {
    if(destino === 'Brasil') {
             console.log('Gire a la izquierda');
    } else if(destino === 'Argentina') {
             console.log('Gire a la derecha');
    } else {
             console.log('Nos perdimos');''
    }
  };
  viajar('Brasil');


  console.log(21 % 5)